runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /img/(.*\.gif)
  static_files: img/\1
  upload: img/.*\.gif
  mime_type: "image/gif"

- url: /img/(.*\.png)
  static_files: img/\1
  upload: img/.*\.png
  mime_type: "image/x-png"

- url: /img/(.*\.jpg)
  static_files: img/\1
  upload: img/.*\.jpg
  mime_type: "image/jpeg"

- url: /viking/(.*\.paa)
  static_files: viking/\1
  upload: viking/.*\.paa
  mime_type: application/octet-stream

- url: /viking/(.*\.dtd)
  static_files: viking/\1
  upload: viking/(.*\.dtd)
  mime_type: application/xml-dtd

- url: /viking/(.*\.xsl)
  static_files: viking/\1
  upload: viking/(.*\.xsl)
  mime_type: text/html

- url: /viking/(.*\.png)
  static_files: viking/\1
  upload: viking/(.*\.png)
  mime_type: "image/png"

- url: /viking/(.*\.css)
  static_files: css/\1
  upload: css/(.*\.css)
  mime_type: "text/css"

- url: /nightmare/(.*\.paa)
  static_files: nightmare/\1
  upload: nightmare/.*\.paa
  mime_type: application/octet-stream

- url: /nightmare/(.*\.dtd)
  static_files: nightmare/\1
  upload: nightmare/(.*\.dtd)
  mime_type: application/xml-dtd

- url: /nightmare/(.*\.xsl)
  static_files: nightmare/\1
  upload: nightmare/(.*\.xsl)
  mime_type: text/html

- url: /nightmare/(.*\.png)
  static_files: nightmare/\1
  upload: nightmare/(.*\.png)
  mime_type: "image/png"

- url: /nightmare/(.*\.css)
  static_files: css/\1
  upload: css/(.*\.css)
  mime_type: "text/css"

- url: /guardian/(.*\.paa)
  static_files: guardian/\1
  upload: guardian/.*\.paa
  mime_type: application/octet-stream

- url: /guardian/(.*\.dtd)
  static_files: guardian/\1
  upload: guardian/(.*\.dtd)
  mime_type: application/xml-dtd

- url: /guardian/(.*\.xsl)
  static_files: guardian/\1
  upload: guardian/(.*\.xsl)
  mime_type: text/html

- url: /guardian/(.*\.png)
  static_files: guardian/\1
  upload: guardian/(.*\.png)
  mime_type: "image/png"

- url: /guardian/(.*\.css)
  static_files: css/\1
  upload: css/(.*\.css)
  mime_type: "text/css"

- url: /whiskey/(.*\.paa)
  static_files: whiskey/\1
  upload: whiskey/.*\.paa
  mime_type: application/octet-stream

- url: /whiskey/(.*\.dtd)
  static_files: whiskey/\1
  upload: whiskey/(.*\.dtd)
  mime_type: application/xml-dtd

- url: /whiskey/(.*\.xsl)
  static_files: whiskey/\1
  upload: whiskey/(.*\.xsl)
  mime_type: text/html

- url: /whiskey/(.*\.png)
  static_files: whiskey/\1
  upload: whiskey/(.*\.png)
  mime_type: "image/png"

- url: /whiskey/(.*\.css)
  static_files: css/\1
  upload: css/(.*\.css)
  mime_type: "text/css"

- url: /toc/(.*\.paa)
  static_files: toc/\1
  upload: toc/.*\.paa
  mime_type: application/octet-stream

- url: /toc/(.*\.dtd)
  static_files: toc/\1
  upload: toc/(.*\.dtd)
  mime_type: application/xml-dtd

- url: /toc/(.*\.xsl)
  static_files: toc/\1
  upload: toc/(.*\.xsl)
  mime_type: text/html

- url: /toc/(.*\.png)
  static_files: toc/\1
  upload: toc/(.*\.png)
  mime_type: "image/png"

- url: /toc/(.*\.css)
  static_files: css/\1
  upload: css/(.*\.css)
  mime_type: "text/css"

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: webapp2
  version: latest

